### ISSUE TITLE
Not working on high Sierra.

### ISSUE THREAD

**Issue by Nera2626** [airbyte/touchbar_santa#1]
The program starts, the music plays, but the Touch Bar doesn't display anything.

My Touch Bar fells useless now.

**Comment by stevysmith** [comment]
@Nera2626 I am so sorry to disappoint. We will bring the spirit of Christmas back to your touchbar soon 🎄

**Comment by stevysmith** [comment]
Good news has arrived @Nera2626 - the app has been updated and 🎅 is back with you on High Sierra.

**Comment by rossbeale** [comment]
🙌
